const CREATE_WORKOUT_GROUPS = `CREATE TABLE IF NOT EXISTS WorkoutGroups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    finished INTEGER DEFAULT 0,
    for_date DATETIME,
    title TEXT NOT NULL,
    caption TEXT DEFAULT "",
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(title)
);`;

const CREATE_WORKOUTS = `CREATE TABLE IF NOT EXISTS Workouts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER,
    title TEXT NOT NULL,
    desc TEXT,
    scheme_type INTEGER DEFAULT 0,
    scheme_rounds TEXT DEFAULT '[]',
    instruction TEXT DEFAULT '',
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES WorkoutGroups(id),
    UNIQUE(group_id, title)
    );`;

const CREATE_WORKOUT_CATEGORIES = `CREATE TABLE IF NOT EXISTS WorkoutCategories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT UNIQUE NOT NULL
    );`;

const CREATE_WORKOUT_NAMES = `CREATE TABLE IF NOT EXISTS WorkoutNames (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    desc TEXT,
    media_ids TEXT DEFAULT '[]',
    primary_category INTEGER,
    secondary_category INTEGER,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (primary_category) REFERENCES WorkoutCategories(id),
    FOREIGN KEY (secondary_category) REFERENCES WorkoutCategories(id)
);`;

const CREATE_WORKOUT_ITEMS = `CREATE TABLE IF NOT EXISTS WorkoutItems (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    workout_id INTEGER,
    name_id INTEGER,
    ssid INTEGER DEFAULT -1,
    constant INTEGER DEFAULT 0,
    sets INTEGER DEFAULT 0,
    reps TEXT DEFAULT '[0]',
    pause_duration REAL DEFAULT 0.00,
    duration TEXT DEFAULT '[0]',
    duration_unit INTEGER DEFAULT 0,
    distance TEXT DEFAULT '[0]',
    distance_unit INTEGER DEFAULT 0,
    weights TEXT DEFAULT '[]',
    weight_unit TEXT DEFAULT 'kg',
    rest_duration REAL DEFAULT 0.0,
    rest_duration_unit INTEGER DEFAULT 0,
    percent_of TEXT DEFAULT '',
    w_order INTEGER,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (workout_id) REFERENCES Workouts(id),
    FOREIGN KEY (name_id) REFERENCES WorkoutNames(id)
);`;
const CREATE_DUAL_WORKOUT_ITEMS = `CREATE TABLE IF NOT EXISTS DualWorkoutItems (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    workout_id INTEGER,
    name_id INTEGER,
    ssid INTEGER DEFAULT -1,
    constant INTEGER DEFAULT 0,
    sets INTEGER DEFAULT 0,
    reps TEXT DEFAULT '[0]',
    pause_duration REAL DEFAULT 0.00,
    duration TEXT DEFAULT '[0]',
    duration_unit INTEGER DEFAULT 0,
    distance TEXT DEFAULT '[0]',
    distance_unit INTEGER DEFAULT 0,
    weights TEXT DEFAULT '[]',
    weight_unit TEXT DEFAULT 'kg',
    rest_duration REAL DEFAULT 0.0,
    rest_duration_unit INTEGER DEFAULT 0,
    percent_of TEXT DEFAULT '',
    r_sets INTEGER DEFAULT 0,
    r_reps TEXT DEFAULT '[0]',
    r_pause_duration REAL DEFAULT 0.00,
    r_duration TEXT DEFAULT '[0]',
    r_duration_unit INTEGER DEFAULT 0,
    r_distance TEXT DEFAULT '[0]',
    r_distance_unit INTEGER DEFAULT 0,
    r_weights TEXT DEFAULT '[]',
    r_weight_unit TEXT DEFAULT 'kg',
    r_rest_duration REAL DEFAULT 0.0,
    r_rest_duration_unit INTEGER DEFAULT 0,
    r_percent_of TEXT DEFAULT '',
    w_order INTEGER,
    finished BOOLEAN DEFAULT 0,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (workout_id) REFERENCES Workouts(id),
    FOREIGN KEY (name_id) REFERENCES WorkoutNames(id)
);`;

const INSERT_WORKOUT_CATEGORIES = `INSERT INTO WorkoutCategories (title) VALUES
("Jiu jitsu"),
("Weightlifting"),
("Powerlifting"),
("Lower body"),
("Upper body"),
("Total body"),
("Boxing"),
("Running"),
("Sprinting"),
("Plyometric"),
("Jumping"),
("Gymnastics"),
("Arms"),
("Legs"),
("Squat"),
("Deadlift"),
("Bench"),
("Clean"),
("Snatch"),
("Press"),
("Overhead press"),
("Back"),
("Core"),
("Shoulder"),
("Lunge"),
("Pullup"),
("Rowing"),
("Cardio");`;

const INSERT_WORKOUT_NAMES = `INSERT INTO WorkoutNames (name, desc, primary_category, secondary_category) VALUES
("Air\ Squat", "Bodyweight squat with arms extended.", 15, 1),
("Back\ Extension", "Lower back strengthening exercise with hands behind the head or across the chest.", 23, 1),
("Bar\ Hang", "Hanging from a bar with arms fully extended to improve grip strength and shoulder mobility.", 22, 1),
("Bar\ Muscle\ Up", "A gymnastics move where an athlete pulls their entire body over a bar and then back down.", 12, 1),
("BB\ Curl", "Weightlifting exercise targeting the biceps, using a barbell and an underhand grip.", 13, 1),
("BB\ Lunge", "Lunge exercise that utilizes a barbell on the back of the shoulders.", 25, 1),
("BB\ Row", "Weightlifting exercise where a barbell is pulled towards the chest while maintaining a flat back.", 22, 1),
("Behind\ the\ Neck\ Press", "Should press starting from behind the neck.", 24, 1),
("Bench\ Press", "Weightlifting exercise performed lying down, targeting the chest, shoulders, and triceps.", 17, 1),
("Block\ Snatch", "Olympic weightlifting movement that involves pulling a barbell from the ground to overhead in one motion, with a pause just above the knees.", 19, 1),
("Box\ Jumps", "Plyometric exercise that involves jumping onto a box.", 10, 10),
("Box\ Squat", "Squat variation that involves sitting back onto a box, then standing up again.", 15, 1),
("Bulgarian\ Split\ Squat", "Lunge variation that involves placing the rear foot on a bench or elevated surface.", 25, 1),
("Burpees", "Full-body exercise that involves squatting, kicking the feet back into a plank, performing a push-up, then returning to a squat and jumping.", 6, 1),
("Chest\ Supported\ Rows", "Row variation whie lying on a bench, targeting the back muscles.", 22, 5),
("Chin-Up", "Pull-up variation with an underhand grip, targeting the biceps and back muscles.", 26, 1),
("Clean", "Olympic weightlifting movement that involves pulling a barbell from the ground to the shoulders.", 18, 1),
("Clean\ and\ Jerk", "Olympic weightlifting movement that involves pulling a barbell from the ground to the shoulders, then pushing it overhead.", 18, 1),
("Close-Grip\ Bench\ Press", "Bench Press variation with a narrower grip, targeting the triceps.", 17, 1),
("Crunch", "Abdominal exercise that involves curling the upper body towards the knees.", 23, 23),
("Cycling", "Cycling.", 28, 28),
("DB\ Bent\ Over\ Row", "Self supported, bent forward dumbbell rows.", 22, 5),
("DB\ Chest\ Fly", "An exercise performed lying down on the back spreading the arms to the side with dumbells.", 5, 1),
("DB\ Chest\ Press", "Chest Press exercise performed with dumbbells instead of a barbell.", 17, 1),
("DB\ Curl", "Bicep curl exercise performed with dumbbells instead of a barbell.", 13, 1),
("DB\ Decline\ Chest\ Press", "Bench Press performed on a decline bench with dumbbells instead of a barbell.", 17, 1),
("DB\ Front\ Raise", "Shoulder exercise that involves lifting dumbbells in front of the body.", 13, 1),
("DB\ Lunge", "Lunge exercise performed with dumbbells.", 25, 1),
("DB\ Pullover", "Back exercise that involves lying on a bench and lowering a dumbbell behind the head.", 22, 1),
("DB\ Rear\ Delt\ Row", "Shoulder exercise that involves lifting dumbbells to the sides of the body.", 22, 1),
("DB\ Romanian\ Deadlift", "Romanian deadlift with dumbbells, targeting the posterior chain muscles of the legs and glutes", 16, 1),
("DB\ Row", "Bent-over row with dumbbells, targeting the back muscles, particularly the lats", 22, 1),
("DB\ Shoulder\ Press", "Shoulder press or overhead press with dumbbells, targeting the shoulder muscles", 21, 1),
("DB\ Shrug", "Shrug movement with dumbbells, targeting the trapezius muscles of the upper back", 5, 1),
("Deadbugs", "Abdominal exercise that involves lying on the back and extending opposite arms and legs.", 23, 1),
("Deadlift", "Weightlifting exercise that targets the lower body and back muscles.", 16, 1),
("Decline\ Bench\ Press", "Bench Press performed on a decline bench, targeting the lower portion of the chest.", 17, 1),
("Deficit\ Deadlift", "Deadlift variation with the feet standing on a platform or weight plate to increase range of motion.", 16, 1),
("Dips", "Dips performed with the body leaning slightly forward to target the triceps and chest.", 13, 13),
("Double\ Unders", "Jump rope exercise that involves passing the rope twice under the feet during each jump.", 10, 1),
("Elliptical", "Carido machine.", 28, 28),
("Farmers\ Walk", "Walking while holding weights in each hand, targeting the grip and overall strength and endurance of the upper body and core", 6, 1),
("Front\ Squat", "Squatting with the barbell resting on the front of the shoulders, targeting the quadriceps, hamstrings, and glutes", 15, 1),
("Goblet\ Squat", "Squatting with a kettlebell or dumbbell held at chest level, targeting the same muscles as the front squat", 15, 1),
("Good\ Morning", "Hinging at the hips while holding a barbell, targeting the posterior chain muscles of the legs and glutes", 14, 1),
("Hammer\ Curl", "Curling dumbbells with a neutral grip, targeting the biceps", 13, 1),
("Hamstring\ Curl", "Machine, targeting the hamstrings", 4, 14),
("Handstand\ Push\ Up", "Pushing the body up while in a handstand position, targeting the shoulder muscles", 24, 1),
("Handstand\ Walk", "Walking on the hands while maintaining a handstand position, targeting the core and upper body strength and stability", 24, 1),
("Hang\ Clean", "Olympic weightlifting movement involving lifting the barbell from a hanging position, targeting the explosive power and strength of the legs and back", 18, 1),
("Hang\ Power\ Clean", "Similar to the hang clean, but the movement ends with the barbell at shoulder height instead of the front rack position", 18, 1),
("Hang\ Power\ Snatch", "Olympic weightlifting movement involving lifting the barbell from a hanging position overhead in one fluid motion, targeting the same muscles as the hang clean", 19, 1),
("Hang\ Snatch", "A variation of the snatch starting off the floor.", 19, 1),
("Hanging\ Leg\ Raises", "Hanging from a bar and raising the legs up to the chest or higher, targeting the core muscles", 23, 1),
("Heel\ Touch", "Lying on the back and touching the heels with the fingertips, targeting the abdominal muscles", 23, 1),
("Hill\ Sprints", "Up hill sprints.", 9, 4),
("Hip\ Abduction", "Moving the legs away from the midline of the body while lying on the side, targeting the hip abductor muscles", 14, 1),
("Hip\ Adduction", "Moving the legs toward the midline of the body while lying on the side, targeting the hip adductor muscles", 14, 1),
("Hip\ Thrust", "Hinging at the hips while the shoulders are elevated on a bench, targeting the glute muscles", 14, 1),
("Incline\ Bench\ Press", "Bench press performed on an inclined bench, targeting the upper portion of the chest muscles", 5, 1),
("Incline\ Dumbbell\ Press", "Dumbbell press performed on an inclined bench, targeting the same muscles as the incline bench press", 5, 1),
("Jogging", "Jogging", 28, 28),
("JuiJitsu", "Martial art involving grappling and submission holds, targeting overall strength, endurance, and flexibility", 1, 1),
("Kettlebell\ Swing", "Swinging a kettlebell between the legs and up to shoulder height, targeting the posterior chain muscles of the legs and glutes", 6, 1),
("Kettlebell\ Front\ Squat", "Front squat with two kettlebells.", 15, 6),
("Kettlebell\ Overhead\ Squat", "Overhead squat with two kettlebells.", 15, 6),
("Landmine", "Exercise involving a barbell anchored at one end and held at the other, targeting various muscle groups depending on the movement", 23, 1),
("Leg\ Extension", "Extension movement of the legs while seated, targeting the quadriceps muscles", 4, 1),
("Leg\ Press", "Pressing weight away with the legs while seated, targeting the same muscles as the squat", 4, 1),
("Leg\ Curl", "Curling the legs toward the buttocks while lying on the stomach, targeting the hamstrings muscles", 4, 1),
("Leg\ Raise", "Lying on the back and raising the legs up to the chest or higher, targeting the abdominal muscles", 4, 1),
("Mountain\ Climbers", "Alternating leg movement resembling climbing, targeting the core and cardiovascular endurance", 23, 1),
("Med\ Ball\ Side\ Toss", "Throw a medicine ball from the hip, across your body.", 23, 23),
("Med\ Ball\ Slam", "Slam mediine ball from overhead to the ground.", 23, 23),
("Overhead\ Squat", "Squatting with the barbell held overhead, targeting the same muscles as the front squat and shoulder muscles", 15, 1),
("Paused\ Deadlift", "Deadlift movement with a pause at the mid-shin level", 16, 1),
("Paused\ Squat", "A squat variation where the lifter pauses at the bottom of the squat for a predetermined amount of time before standing back up.", 15, 1),
("Pendlay\ Row", "A type of rowing exercise where the barbell is lifted off the ground for each repetition and then lowered back down in a controlled manner.", 22, 1),
("Plank", "An isometric exercise where the body is held in a straight line from head to heels in a push-up position, with the elbows or hands on the ground.", 23, 1),
("Power\ Clean", "A weightlifting exercise where the barbell is explosively lifted from the ground to the shoulders in one motion.", 18, 1),
("Power\ Jerk", "A weightlifting exercise where the barbell is explosively lifted from the shoulders to overhead, with a slight dip of the legs before driving the barbell up with the arms and legs.", 21, 1),
("Power\ Snatch", "A weightlifting exercise where the barbell is explosively lifted from the ground to overhead in one motion.", 19, 1),
("Pull\ Up", "An upper body exercise where the body is lifted up towards a bar with the arms until the chin is above the bar.", 26, 1),
("Push\ Press", "A weightlifting exercise where the barbell is lifted from the shoulders to overhead with the assistance of the legs.", 21, 1),
("Push-Up", "An exercise where the body is lowered towards the ground and then pushed back up using the arms and chest muscles.", 5, 1),
("Reverse\ Flyes", "An exercise where the arms are lifted away from the body in a reverse motion, targeting the muscles of the upper back and shoulders.", 22, 1),
("Reverse\ Hyper\ Ext", "An exercise machine where the lower body is suspended in the air while the upper body is held in place, targeting the lower back and glutes.", 23, 1),
("Ring\ Handstand\ Push\ Up", "An exercise where the body is held in a handstand position using gymnastic rings for support.", 24, 1),
("Ring\ Muscle\ Up", "A gymnastic exercise where the body is lifted up and over the rings, targeting the muscles of the upper body.", 22, 1),
("Romanian\ Deadlift", "A deadlift variation where the barbell is lowered to the shins and then lifted back up, targeting the muscles of the lower back and hamstrings.", 16, 1),
("Rolling\ Sesh", "Bump n tap.", 1, 1),
("Rope\ Climbing", "An exercise where the body is pulled up a rope using the arms and upper body strength.", 6, 1),
("Rowing", "A cardiovascular exercise where the body is propelled forward on a machine using a rowing motion.", 22, 1),
("Running", "A cardiovascular exercise where the body runs or jogs on a treadmill or outside.", 8, 1),
("Shoulder\ Press", "Shoulder press or overhead press with a barbell, targeting the shoulder muscles", 21, 1),
("Side\ Plank", "An isometric exercise where the body is held in a straight line from head to heels in a side position, with one elbow or hand on the ground.", 23, 1),
("Sit-Up", "An exercise where the body is lifted from a lying down position to a seated position using the abdominal muscles.", 23, 1),
("Snatch", "A weightlifting exercise where the barbell is lifted from the ground to overhead in one motion.", 19, 1),
("Snatch\ Grip\ Behind\ the\ Neck\ Press", "A variation of the snatch exercise where the lifter uses a wider grip on the barbell.", 21, 1),
("Snatch\ Grip\ Deadlift", "A deadlift performed with a snatch grip.", 16, 1),
("Split\ Jerk", "A weightlifting exercise where the barbell is lifted from the shoulders to overhead with a split stance of the legs.", 21, 1),
("Sprint", "A high intensity cardiovascular exercise where the body runs or sprints at a fast pace.", 9, 1),
("Squat", "An exercise where the body is lowered down into a sitting position and then lifted back up, targeting the muscles of the legs and glutes.", 15, 1),
("Squat\ Jerk", "A weightlifting exercise where the barbell is lifted from the shoulders to overhead with a squat stance of the legs.", 21, 1),
("Stairs", "Stairs/ stairmaster/ stairclimber.", 28, 28),
("Step\ Up", "An exercise where the body steps up onto a platform or bench using the leg muscles.", 4, 1),
("Sumo\ Deadlift", "A deadlift variation where the feet are placed in a wider stance and the grip is between the legs, targeting the muscles of the inner thighs and lower back.", 16, 1),
("Thruster", "A weightlifting exercise where the barbell is lifted from the shoulders to overhead with", 6, 1),
("Tricep\ Extension", "Tricep extension is an isolation exercise that targets the triceps muscles. It is typically performed with a cable machine or dumbbell, and involves extending the arm at the elbow joint to activate the triceps.", 13, 1),
("Walking", "Walking.", 28, 28),
("Wall\ Balls", "Wall balls are a functional fitness exercise that involves throwing a weighted ball against a wall and catching it as it comes back down. This exercise targets several muscle groups including the legs, hips, core, shoulders, and arms. It is often used in CrossFit and other high-intensity training programs.", 6, 1),
("Windshield\ Wiper", "The windshield wiper exercise is a core strengthening exercise that targets the obliques and lower abs. It involves lying on the back with the legs raised and extended, and then moving the legs from side to side in a windshield wiper motion. This exercise is typically performed on a mat or bench, and can be modified to increase or decrease the difficulty level.", 23, 1);`;

export {
  CREATE_WORKOUTS,
  CREATE_WORKOUT_CATEGORIES,
  CREATE_WORKOUT_GROUPS,
  CREATE_WORKOUT_ITEMS,
  CREATE_DUAL_WORKOUT_ITEMS,
  CREATE_WORKOUT_NAMES,
  INSERT_WORKOUT_NAMES,
  INSERT_WORKOUT_CATEGORIES,
};
